"""Add is_admin column

Revision ID: 75df9989090c
Revises: 
Create Date: 2024-12-16 19:12:48.308064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75df9989090c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
